name: 'AI Test Writer'
description: 'Analyzes code coverage and suggests test improvements'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true
  coverage-path:
    description: 'Path to the coverage JSON file'
    default: 'cover/coverage.json'
    required: false
  pr-number:
    description: 'Pull request number (for workflow_dispatch events)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: cd ${{ github.action_path }} && npm install
      shell: bash
      
    - name: Build action
      run: cd ${{ github.action_path }} && npm run build
      shell: bash
      
    - name: Run action
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_ANTHROPIC-API-KEY: ${{ inputs.anthropic-api-key }}
        INPUT_COVERAGE-PATH: ${{ inputs.coverage-path }}
        INPUT_PR-NUMBER: ${{ inputs.pr-number }}
