name: 'AI Code Analyzer'
description: 'Analyzes code changes in PRs against custom AI rules'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true
  rules-path:
    description: 'Path to the rules directory'
    default: '.ai-code-rules'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: cd ${{ github.action_path }} && npm install
      shell: bash
      
    - name: Build action
      run: cd ${{ github.action_path }} && npm run build
      shell: bash
      
    - name: Run action
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_ANTHROPIC-API-KEY: ${{ inputs.anthropic-api-key }}
        INPUT_RULES-PATH: ${{ inputs.rules-path }}
